services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: agent-backend
    restart: unless-stopped
    ports:
      # Map host port 7777 to container port 7777
      - "7777:7777"
    environment:
      # Pass the API key from the .env file
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      # AGENT_PROFILE_PATH can also be set in .env or defaults here
      - AGENT_PROFILE_PATH=${AGENT_PROFILE_PATH:-config/agents/standard-profiles/standard-agent-MK1/standard-agent-MK1.yml}
      # AGENT_WORKSPACE is critical for the C++ file tool and script sandboxing
      - AGENT_WORKSPACE=/app/agent_workspace
    volumes:
      # Mount the local agent_workspace into the container for persistent data
      - ./agent_workspace:/app/agent_workspace
      # For development, you might want to mount configs and prompts to see changes live:
      # However, for a "production" build from this Dockerfile, they are baked in.
      # If you uncomment these, changes on the host will reflect in the container.
      # - ./prompts:/app/prompts:ro
      # - ./config:/app/config:ro
    user: agentuser
    networks:
      - agent-net

networks:
  agent-net:
    driver: bridge
