from pydantic import BaseModel, Field
from typing import List, Optional, Dict, Any, Literal
import datetime

# --- Unified Request Models ---_-
class ChatMessage(BaseModel):
    role: Literal["user", "assistant", "system"] = "user"
    content: str

class ChatCompletionRequest(BaseModel):
    provider: str = Field(..., description="Identifier for the AI provider (e.g., 'gemini', 'groq', 'openai_compatible').")
    model: Optional[str] = Field(None, description="Specific model name for the provider (e.g., 'gemini-1.5-flash-latest', 'llama3-8b-8192'). If None, provider's default is used.")
    messages: List[ChatMessage]
    max_tokens: Optional[int] = Field(150, gt=0, description="Maximum number of tokens to generate.")
    temperature: Optional[float] = Field(0.7, ge=0.0, le=2.0, description="Sampling temperature.")
    stream: Optional[bool] = Field(False, description="Whether to stream the response (Not fully supported in this stub version for all providers).")
    # Add other common parameters like top_p, presence_penalty, etc. as needed

# --- Unified Response Models ---_-
class ChatCompletionChoice(BaseModel):
    index: int
    message: ChatMessage
    finish_reason: Optional[str] = None # e.g., "stop", "length", "content_filter"

class UsageStats(BaseModel):
    prompt_tokens: Optional[int] = None
    completion_tokens: Optional[int] = None
    total_tokens: Optional[int] = None

class ChatCompletionResponse(BaseModel):
    id: str # A unique ID for the response, generated by the gateway or provider
    object: str = "chat.completion" # OpenAI-like object type
    created: int = Field(default_factory=lambda: int(datetime.datetime.now(datetime.timezone.utc).timestamp()))
    model: str # The model that handled the request
    provider: str # The provider that handled the request
    choices: List[ChatCompletionChoice]
    usage: Optional[UsageStats] = None
    # system_fingerprint: Optional[str] = None # If provider includes it

# --- Error & System Models ---_-
class ErrorDetailResponse(BaseModel):
    detail: Any # Can be string or more structured error from provider

class HealthStatus(BaseModel):
    app_name: str
    version: str
    status: str = "healthy"
    timestamp: datetime.datetime
    # available_providers: List[str] # Could list configured providers

class ProviderCapability(BaseModel):
    provider_id: str
    status: Literal["configured", "key_missing", "simulated", "error"]
    default_model: Optional[str] = None
    notes: Optional[str] = None

class SystemCapabilitiesResponse(BaseModel):
    app_name: str
    version: str
    description: str
    supported_providers: List[ProviderCapability]
    endpoints: List[Dict[str, str]]
