import logging
import os
from typing import List, Optional
import aiofiles.os as aios

from sqlalchemy.ext.asyncio import create_async_engine, AsyncSession
from sqlalchemy.orm import sessionmaker
from sqlalchemy import select, delete

from app.config_registry import settings
from app.models_registry import AssetMetadataDB, Base

logger = logging.getLogger(__name__)

_ASYNC_ENGINE = None
_AsyncSessionFactory = None

def get_engine():
    global _ASYNC_ENGINE
    if _ASYNC_ENGINE is None:
        logger.info(f"Creating SQLAlchemy engine for: {settings.REGISTRY_SQLALCHEMY_DATABASE_URL}")
        _ASYNC_ENGINE = create_async_engine(settings.REGISTRY_SQLALCHEMY_DATABASE_URL, echo=(settings.LOG_LEVEL.upper() == "DEBUG"))
    return _ASYNC_ENGINE

def get_async_session_factory():
    global _AsyncSessionFactory
    if _AsyncSessionFactory is None:
        engine = get_engine()
        _AsyncSessionFactory = sessionmaker(engine, class_=AsyncSession, expire_on_commit=False)
    return _AsyncSessionFactory

async def init_db():
    engine = get_engine()
    async with engine.begin() as conn:
        await conn.run_sync(Base.metadata.create_all)
    logger.info("Database tables checked/created.")

async def close_db_connection():
    global _ASYNC_ENGINE
    if _ASYNC_ENGINE:
        await _ASYNC_ENGINE.dispose()
        _ASYNC_ENGINE = None
        logger.info("SQLAlchemy engine disposed.")

async def save_asset_metadata(asset_metadata: AssetMetadataDB) -> AssetMetadataDB:
    factory = get_async_session_factory()
    async with factory() as session:
        async with session.begin():
            session.add(asset_metadata)
        await session.refresh(asset_metadata) # To get defaults like ID if generated by DB
        logger.info(f"Saved metadata for asset ID: {asset_metadata.id}")
        return asset_metadata

async def get_asset_metadata_by_id(asset_id: str) -> Optional[AssetMetadataDB]:
    factory = get_async_session_factory()
    async with factory() as session:
        result = await session.execute(select(AssetMetadataDB).where(AssetMetadataDB.id == asset_id))
        return result.scalar_one_or_none()

async def list_all_asset_metadata(skip: int = 0, limit: int = 100) -> List[AssetMetadataDB]:
    factory = get_async_session_factory()
    async with factory() as session:
        result = await session.execute(
            select(AssetMetadataDB).order_by(AssetMetadataDB.upload_timestamp.desc()).offset(skip).limit(limit)
        )
        return result.scalars().all()

async def delete_asset_metadata_and_file(asset_id: str) -> bool:
    factory = get_async_session_factory()
    asset_metadata = await get_asset_metadata_by_id(asset_id)
    if not asset_metadata:
        logger.warning(f"Asset metadata not found for ID: {asset_id}. Cannot delete.")
        return False

    # Delete from DB first
    async with factory() as session:
        async with session.begin():
            stmt = delete(AssetMetadataDB).where(AssetMetadataDB.id == asset_id)
            db_result = await session.execute(stmt)
            if db_result.rowcount == 0:
                logger.warning(f"Asset ID {asset_id} was not found in DB during delete operation, though metadata was fetched prior.")
                return False # Should not happen if metadata was fetched
    
    logger.info(f"Deleted asset metadata from DB for ID: {asset_id}")

    # Delete the actual file
    file_path = os.path.join(settings.UPLOADED_ASSETS_DIR_CONTAINER, asset_metadata.stored_filename)
    try:
        if await aios.path.exists(file_path):
            await aios.remove(file_path)
            logger.info(f"Successfully deleted asset file: {file_path}")
        else:
            logger.warning(f"Asset file not found for deletion: {file_path}. Metadata was {asset_metadata.id}")
    except Exception as e:
        logger.error(f"Error deleting asset file {file_path}: {e}. DB record was deleted.", exc_info=True)
        # Consider implications: DB record gone, file might still exist.  For now, log and proceed.
        
    return True
